spring:
  datasource:
    url: jdbc:mysql://192.168.5.111:3124/cloud_do?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: xc_dev
    password: E7F@oFw2Ks
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.111:4848
        namespace: dev
        username: nacos
        password: zwcb3axb
  data:
    redis:
      host: 192.168.5.111
      port: 26379
      password: X4!A@iq#HM
      database: 12

# Sa-Token 配置
sa-token:
  sso-client:
    # SSO-Server端主机地址
    server-url: http://127.0.0.1:11000
    client: system
    # 配置Sa-Token单独使用的Redis连接 （此处需要和SSO-Server端连接同一个Redis）
  alone-redis:
    host: 192.168.5.111
    port: 26379
    password: X4!A@iq#HM
    database: 12
    # 连接超时时间
    timeout: 10s